//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enlimahotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_enlimahotelEntities : DbContext
    {
        public db_enlimahotelEntities()
            : base("name=db_enlimahotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_hotel> tbl_hotel { get; set; }
        public virtual DbSet<tbl_kamar> tbl_kamar { get; set; }
        public virtual DbSet<tbl_pelanggan> tbl_pelanggan { get; set; }
        public virtual DbSet<tbl_pelayanan> tbl_pelayanan { get; set; }
        public virtual DbSet<tbl_pesanan> tbl_pesanan { get; set; }
        public virtual DbSet<tbl_reservasi> tbl_reservasi { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
