//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enlimahotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reservasi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_reservasi()
        {
            this.tbl_pesanan = new HashSet<tbl_pesanan>();
        }
    
        public string reservasi_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> pelanggan_id { get; set; }
        public Nullable<int> kamar_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> tanggal_checkin { get; set; }
        public Nullable<System.DateTime> tanggal_checkout { get; set; }
        public Nullable<int> jumlah_tamu { get; set; }
        public Nullable<bool> sarapan { get; set; }
        public Nullable<bool> extra_bed { get; set; }
        public Nullable<int> total_bayar { get; set; }
    
        public virtual tbl_kamar tbl_kamar { get; set; }
        public virtual tbl_pelanggan tbl_pelanggan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pesanan> tbl_pesanan { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
