//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enlimahotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hotel
    {
        public int hotel_id { get; set; }
        public string nama_hotel { get; set; }
        public string alamat { get; set; }
        public string nomor_telepon { get; set; }
        public byte[] logo_hotel { get; set; }
        public Nullable<int> kapasitas_kamar { get; set; }
    }
}
