//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enlimahotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pelanggan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_pelanggan()
        {
            this.tbl_reservasi = new HashSet<tbl_reservasi>();
        }
    
        public int pelanggan_id { get; set; }
        public string nama { get; set; }
        public string email { get; set; }
        public string nomor_telepon { get; set; }
        public string jenis_identitas { get; set; }
        public string no_identitas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_reservasi> tbl_reservasi { get; set; }
    }
}
