//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enlimahotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pelayanan
    {
        public int pelayanan_id { get; set; }
        public string nama_pelayanan { get; set; }
        public Nullable<int> harga_pelayanan { get; set; }
        public string kategori { get; set; }
    }
}
