//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enlimahotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pesanan
    {
        public int pesanan_id { get; set; }
        public string reservasi_id { get; set; }
        public Nullable<int> pelayanan_id { get; set; }
        public Nullable<int> harga { get; set; }
    
        public virtual tbl_reservasi tbl_reservasi { get; set; }
    }
}
