//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enlimahotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kamar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kamar()
        {
            this.tbl_reservasi = new HashSet<tbl_reservasi>();
        }
    
        public int kamar_id { get; set; }
        public string jenis_kamar { get; set; }
        public Nullable<int> tarif_kamar { get; set; }
        public byte[] foto_kamar { get; set; }
        public Nullable<System.DateTime> tersedia { get; set; }
        public Nullable<bool> extra_bed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_reservasi> tbl_reservasi { get; set; }
    }
}
